kind: PersistentVolume
apiVersion: v1
metadata:
  name: vp-volume-minio
  labels:
    type: local
    app: minio
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: minio-data-claim # Sets name of PV
spec:
  accessModes:
    - ReadWriteOnce # Sets read and write access
  resources:
    requests:
      storage: 10Gi # Sets volume size
