apiVersion: v1
kind: Service
metadata:
  name: vp-minio # Sets service name
  labels:
    app: vp-minio # Labels and Selectors
spec:
  type: ClusterIP # Sets service type
  ports:
    - port: 9000
      name: http
  selector:
    app: minio
