apiVersion: v1
kind: Service
metadata:
  name: vp-minio-ui # Sets service name
  labels:
    app: vp-minio-ui # Labels and Selectors
spec:
  type: ClusterIP # Sets service type
  ports:
    - port: 9001
      name: http
  selector:
    app: minio
