apiVersion: v1
kind: Service
metadata:
  name: vp-backend # Sets service name
  labels:
    app: vp-backend # Labels and Selectors
spec:
  type: ClusterIP # Sets service type
  ports:
    - port: 3000
      name: http
  selector:
    app: node
