FROM node:18-alpine AS build
WORKDIR /app
COPY package.json ./
RUN npm install --force
COPY . ./
RUN npm run build

FROM nginx:1.23.1-alpine
RUN rm -rf /usr/share/nginx/html/*
RUN rm /etc/nginx/nginx.conf
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist/vp-ui /usr/share/nginx/html
