version: "3.9"

services:

  # Service for the database
  vp-db:
    container_name: vp-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: vp
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  vp-mailhog:
    container_name: vp-mailhog
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MH_STORAGE: maildir
    volumes:
      - smtp_data:/maildir

  vp-minio:
    image: minio/minio
    container_name: vp-minio
    ports:
      - "9030:9000"
      - "9031:9001"
    volumes:
      - vp-minio_storage:/data
    environment:
      MINIO_ROOT_USER: userminio
      MINIO_ROOT_PASSWORD: BigSecret
    command: server --console-address ":9001" /data

volumes:
  db-data:
  smtp_data:
  pgadmin-data:
  vp-minio_storage: