version: "3.9"

services:

  # Service for the database
  vp-db:
    container_name: vp-db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data

  # Service for the backend
  vp-api:
    container_name: vp-api
    image: bastiansmn/visual-productivity:server-latest
    environment:
      API_PATH: ${API_PATH}
      PORT: ${PORT}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      VP_ALLOWED_ORIGINS: ${VP_ALLOWED_ORIGINS}
      VP_ALLOWED_METHODS: ${VP_ALLOWED_METHODS}
      VP_ALLOWED_HEADERS: ${VP_ALLOWED_HEADERS}
      VP_REGISTER_PATTERN: ${VP_REGISTER_PATTERN}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - vp-db

volumes:
  db-data: