version: "3.9"

services:

  # Service for the database
  vp-db:
    container_name: vp-db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data

  # Service for the backend
  vp-api:
    container_name: vp-api
    image: bastiansmn/visual-productivity:server-latest
    environment:
      API_PATH: ${API_PATH}
      PORT: ${PORT}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      VP_ALLOWED_ORIGINS: ${VP_ALLOWED_ORIGINS}
      VP_ALLOWED_METHODS: ${VP_ALLOWED_METHODS}
      VP_ALLOWED_HEADERS: ${VP_ALLOWED_HEADERS}
      VP_REGISTER_PATTERN: ${VP_REGISTER_PATTERN}
      JWT_SECRET: ${JWT_SECRET}
      ORIGIN: ${ORIGIN}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_TEMP_FOLDER: ${S3_TEMP_FOLDER}
      S3_USER_BUCKET: ${S3_USER_BUCKET}
      S3_PROJECT_BUCKET: ${S3_PROJECT_BUCKET}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - vp-db
      - vp-minio

  vp-minio:
    image: minio/minio
    container_name: vp-minio
    ports:
      - "9030:9000"
      - "9031:9001"
    volumes:
      - vp-minio_storage:/data
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    command: server --console-address ":9001" /data

volumes:
  db-data:
  vp-minio_storage:

networks:
  default:
    name: apps-network
