apiVersion: v1
kind: Service
metadata:
  name: vp-db # Sets service name
  labels:
    app: vp-db # Labels and Selectors
spec:
  type: ClusterIP # Sets service type
  ports:
    - port: 5432
      name: http
  selector:
    app: db
