apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:15.2
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "laponie-gouv"
          envFrom:
          - secretRef:
              name: vp-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              subPath: vp-db
              name: postgres-data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: vp-db-pvc
