apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: workload
                operator: In
                values:
                - application
      containers:
        - name: db
          image: postgres:15.2
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          envFrom:
          - secretRef:
              name: vp-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              subPath: data
              name: postgres-data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data-claim
