apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vp

resources:
- ingress.yml
- backend/backend-deployment.yml
- backend/backend-service.yml
- frontend/frontend-deployment.yml
- frontend/frontend-service.yml
- database/db-deployment.yml
- database/db-service.yml
- database/db-pvc.yml
